config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  root 'static_pages#home'
  get  'pricing' => 'static_pages#pricing'

  devise_for :users, controllers: { registrations: 'registrations' }
  resources :users, only: [:show]

  resources :subscriptions, only: [:new]

  mount StripeEvent::Engine => '/webhooks'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new

    if user.has_role? :admin
      can :manage, :all
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/concerns/price_converter.rb
module PriceConverter
  extend ActiveSupport::Concern

  def get_real_price
    self.amount.to_f / 100.0
  end
end

app/models/plan.rb
class Plan < ActiveRecord::Base
  include PriceConverter

  before_create :create_stripe_plan

  has_many :subscriptions

  validates_presence_of :amount
  validates_presence_of :interval
  validates_presence_of :stripe_plan_id
  validates_presence_of :name

  validates_uniqueness_of :stripe_plan_id

  scope :by_price, -> { order(amount: :desc)}

  def create_stripe_plan
    Honeypack::PlanService.create_stripe_plan(self)
  end

end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  def access_denied(exception)
    redirect_to main_app.root_url, :alert => exception.message
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home; end

  def pricing
    @plans = Plan.by_price
  end
end

app/controllers/subscritions_controller.rb
class SubscritionsController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:show]
  before_action :correct_user,       only: [:show]
  before_action :find_user,          only: [:show]

  def show; end

  private

  def correct_user
    if current_user != User.find_by(id: params[:id])
      redirect_to root_url
    end
  end

  def find_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/subscritions_helper.rb
module SubscritionsHelper
end

app/views/layouts/_header.html.haml
%nav.navbar.navbar-inverse
  .container
    .navbar-header
      %button.navbar-toggle.collapsed{ aria: { controls: 'navbar', expanded: 'false' }, data: { target: '#navbar', toggle: 'collapse' }, type: 'button' }
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to 'New app', root_path, class: 'navbar-brand'
    #navbar.collapse.navbar-collapse
      %ul.nav.navbar-nav.navbar-right
        - if user_signed_in?
          %li
            = link_to current_user do
              %span.glyphicon.glyphicon-user{ aria: { hidden: 'true' } }
              = current_user.name
          %li
            = link_to 'Logout', destroy_user_session_path, method: :delete
        - else
          %li
            = link_to 'Sign up', new_user_registration_path
          %li
            = link_to 'Log in', new_user_session_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title
      App name | #{yield(:title)}
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = render 'layouts/header'
    .container
      - flash.each do |message_type, message|
        %div{ class: "alert alert-#{message_type}", role: 'alert' }
          = message
      = yield

app/views/static_pages/home.html.haml
- provide(:title, 'Home page')
%p Home Page of Lunchy

app/views/static_pages/pricing.html.haml
- provide(:title, 'Pricing page')

%ul.thumbnails.koudoku-pricing-table
  - @plans.each do |plan|
    %li{ :class => 'span3 plan' }
      .thumbnail
        .caption
          %h3= plan.name
          %h4= plan.get_real_price
          .call-to-action
            - if @subscription.nil?
              = link_to 'buy', new_subscription_path(plan: plan.id), class: 'btn btn-success btn-large'

app/views/users/show.html.haml
- provide(:title, @user.name)
.row
  .col-md-6
    %table.table
      %tr
        %td Name:
        %td
          = @user.name
= link_to 'Edit profile', edit_user_registration_path